- hosts: localhost
  connection: local
  become: true 

  tasks:
  - name: Install packages redhat 
    import_tasks: tasks/redhat.yml
    when: ansible_facts['os_family']|lower == 'redhat'

  - name: Install packages debian
    import_tasks: tasks/debian.yml 
    when: ansible_facts['os_family']|lower == 'debian' 
   
